CREATE TABLE PRICES (
    ID SERIAL PRIMARY KEY,
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    END_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE NUMERIC(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    CONSTRAINT chk_dates CHECK (END_DATE > START_DATE)
);
